# =========================
# Spring Boot Application
# =========================
spring.application.name=HospitalReservation
server.port=${PORT:8081}

# =========================
# Database Configuration (PostgreSQL - Render)
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d31tlb7diees73899u8g-a.oregon-postgres.render.com:5432/hospital_reservation_db?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hospital_reservation_db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Hikari Connection Pool (Fix cold start issue)
# =========================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.validation-timeout=5000

# =========================
# Hibernate (JPA)
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Razorpay Configuration
# =========================
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# =========================
# Logging
# =========================
logging.level.org.springframework=INFO
logging.level.com.shirishkanoje=DEBUG

# =========================
# Misc
# =========================
spring.jmx.enabled=false
