# version: "3.8"

# services:

#   mysql:
#     image: mysql:8
#     container_name: mysql_db_docker
#     ports:
#       - "3307:3306"   # host 3307 → container 3306
#     environment:
#       MYSQL_ROOT_PASSWORD: shirish
#       MYSQL_DATABASE: hospital_reservation
#       MYSQL_USER: root
#       MYSQL_PASSWORD: shirish
#     volumes:
#       - ./mysql_data:/var/lib/mysql
    
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin
#     ports:
#       - "8082:80"
#     environment:
#       PMA_HOST: mysql
#       PMA_PORT: 3306
#       PMA_USER: root
#       PMA_PASSWORD: shirish
#     depends_on:
#       - mysql

#   springboot:
#     build: .
#     container_name: scm_springboot_project
#     ports:
#       - "8081:8080"   # host 8081 → Spring Boot inside Docker (8080)
#     depends_on:
#       - mysql
#     environment:
#       # Spring Boot app
#       APP_NAME: HospitalReservation
#       SERVER_PORT: 8080

#       # Database Config
#       MYSQL_HOST: mysql   # connects to mysql container
#       MYSQL_PORT: 3306
#       MYSQL_DB: hospital_reservation
#       MYSQL_USER: root
#       MYSQL_PASSWORD: shirish

#       # JPA / Hibernate
#       HIBERNATE_DDL: update
#       SHOW_SQL: "true"
#       FORMAT_SQL: "true"

#       # Thymeleaf
#       THYMELEAF_CACHE: "false"

#       # Razorpay
#       RAZORPAY_KEY_ID: rzp_test_As5V0saQWOBFcT
#       RAZORPAY_KEY_SECRET: zFPeQXPzDJWSc4D5VDtOQg1b

#       # Logging
#       SPRING_LOG_LEVEL: INFO
#       APP_LOG_LEVEL: DEBUG
#       JMX_ENABLED: "false"

# volumes:
#   mysql_data:
